<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-DTBN5AF" failures="1" tests="2" name="EdgeTest" time="123.621" errors="0" timestamp="2022-02-13T23:14:56 IST">
  <testcase classname="actitimeTest.AllinOneActiTimeTestNG" name="createNewTask" time="0.236">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [http://localhost/user/submit_tt.do] but found [http://localhost/login.do],
	expected [actiTIME - Enter Time-Track] but found [actiTIME - Login]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [http://localhost/user/submit_tt.do] but found [http://localhost/login.do],
expected [actiTIME - Enter Time-Track] but found [actiTIME - Login]
at actitimeTest.AllinOneActiTimeTestNG.createNewTask(AllinOneActiTimeTestNG.java:152)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- createNewTask -->
  <testcase classname="actitimeTest.AllinOneActiTimeTestNG" name="enterTimeTrackPage" time="7.631"/>
  <testcase classname="actitimeTest.AllinOneActiTimeTestNG" name="setDeadlineforOpenTask" time="0.0">
    <ignored/>
  </testcase> <!-- setDeadlineforOpenTask -->
</testsuite> <!-- EdgeTest -->
